---
title: "Softball 2022 Hitting: AUM vs. Gulf South Conference"
author: "William Easter, Jr."
date: "3/5/2023"
output:
  pdf_document: default
  html_document:
    df_print: paged
  word_document: default
---





```{r, message=FALSE,echo=FALSE,results=FALSE}
library(HistData)
library(tidyverse)
library(zeallot)
library(ggplot2)
library(gridExtra)
# Set the working directory to where the CSV file is located
setwd("C:/Users/weyen/OneDrive/Documents/Warhawk Softball/Warhawk-Softball")

# Import the CSV file using read.csv()
wh <- read.csv("2022 GSC SOFTBALL HITTING.csv")
#wh

summary(wh)
c(q1,md,mm,q3)%<-%summary(wh)[2:5]
mad_values <- apply(wh[,3:ncol(wh)],2, mad)
mad_values
iqr<-q3<-q1
iqr
apply(wh[, 3:ncol(wh)], 2, fivenum)

AUM<-wh %>% filter(School == "Auburn Montgomery")
UAH<-wh %>% filter(School == "Alabama Huntsville")
GSC<-wh %>% filter(School != "Auburn Montgomery")
GSC
UAH
AUM
```


# Leauge-wise Batting Average Visualisation
```{r, echo=FALSE, fig.width = 100, fig.asp = 4}

bp_AVG_AUM<-AUM %>% 
  ggplot(aes(AVG)) +
  geom_boxplot(color="orange", fill="black", size=.2, outlier.shape = 7)+ggtitle("AUM Boxplot")

bp_AVG_UAH<-UAH %>% 
  ggplot(aes(AVG)) +
  geom_boxplot(color="blue", fill="black", size=.2, outlier.shape = 7)+ggtitle("UAH Boxplot")

bp_AVG_GSC<-GSC %>% 
  ggplot(aes(AVG)) +
  geom_boxplot(color="red", fill="yellow", size=.2, outlier.shape = 7)+ggtitle("GSC Boxplot")

qq_AVG_AUM<-ggplot(AUM, aes(sample = AVG)) +
  geom_qq()+ggtitle("AUM qq Plot")

qq_AVG_UAH<-ggplot(UAH, aes(sample = AVG)) +
  geom_qq()+ggtitle("UAH qq Plot")

qq_AVG_GSC<-ggplot(GSC, aes(sample = AVG)) +
  geom_qq()+ggtitle("GSC qq Plot")

d_AVG_AUM<-AUM %>% ggplot(aes(AVG)) +
  geom_density(fill="orange", adjust=.1)+ggtitle("AUM Density Plot")

d_AVG_UAH<-UAH %>% ggplot(aes(AVG)) +
  geom_density(fill="blue", adjust=.1)+ggtitle("UAH Density Plot")

d_AVG_GSC<-GSC %>% ggplot(aes(AVG)) +
  geom_density(color='yellow',fill="red", adjust=.1)+ggtitle("GSC Density Plot")

h_AVG_AUM<-AUM %>% 
  ggplot(aes(AVG)) + 
  geom_histogram(color='black', fill='orange',bins=10)+ggtitle("AUM Histogram")

h_AVG_UAH<-UAH %>% 
  ggplot(aes(AVG)) + 
  geom_histogram(color='black', fill='blue',bins=10)+ggtitle("UAH Histogram")

h_AVG_GSC<-GSC %>% 
  ggplot(aes(AVG)) + 
  geom_histogram(color='yellow', fill='red',bins=10)+ggtitle("GSC Histogram")

b_AVG_AUM<-AUM %>% ggplot(aes(AVG)) + geom_bar(color= 'orange', fill='black')+ggtitle("AUM Barplot")

b_AVG_UAH<-UAH %>% ggplot(aes(AVG)) + geom_bar(color= 'blue', fill='black')+ggtitle("AUM Barplot")

b_AVG_GSC<-GSC %>% ggplot(aes(AVG)) + geom_bar(color= 'red', fill='yellow')+ggtitle("GSC Barplot")

grid.arrange(bp_AVG_AUM,bp_AVG_UAH,bp_AVG_GSC,qq_AVG_AUM,qq_AVG_UAH,qq_AVG_GSC,
             d_AVG_AUM,d_AVG_UAH,d_AVG_GSC,h_AVG_AUM,h_AVG_UAH,h_AVG_GSC,
             b_AVG_AUM,b_AVG_UAH,b_AVG_GSC, ncol = 3 )
``` 
# Leauge-wise OPS Visualisation

```{r, echo=FALSE, fig.width = 15, fig.asp = 2}

bp_OPS_AUM<-AUM %>% 
  ggplot(aes(OPS)) +
  geom_boxplot(color="orange", fill="black", size=.2, outlier.shape = 7)+ggtitle("AUM Boxplot")

bp_OPS_UAH<-UAH %>% 
  ggplot(aes(OPS)) +
  geom_boxplot(color="blue", fill="black", size=.2, outlier.shape = 7)+ggtitle("UAH Boxplot")

bp_OPS_GSC<-GSC %>% 
  ggplot(aes(OPS)) +
  geom_boxplot(color="red", fill="yellow", size=.2, outlier.shape = 7)+ggtitle("GSC Boxplot")

qq_OPS_AUM<-ggplot(AUM, aes(sample = OPS)) +
  geom_qq()+ggtitle("AUM qq Plot")

qq_OPS_UAH<-ggplot(UAH, aes(sample = OPS)) +
  geom_qq()+ggtitle("UAH qq Plot")

qq_OPS_GSC<-ggplot(GSC, aes(sample = OPS)) +
  geom_qq()+ggtitle("GSC qq Plot")

d_OPS_AUM<-AUM %>% ggplot(aes(OPS)) +
  geom_density(fill="orange", adjust=.1)+ggtitle("AUM Density Plot")

d_OPS_UAH<-UAH %>% ggplot(aes(OPS)) +
  geom_density(fill="blue", adjust=.1)+ggtitle("UAH Density Plot")

d_OPS_GSC<-GSC %>% ggplot(aes(OPS)) +
  geom_density(color='yellow',fill="red", adjust=.1)+ggtitle("GSC Density Plot")

h_OPS_AUM<-AUM %>% 
  ggplot(aes(OPS)) + 
  geom_histogram(color='black', fill='orange',bins=10)+ggtitle("AUM Histogram")

h_OPS_UAH<-UAH %>% 
  ggplot(aes(OPS)) + 
  geom_histogram(color='black', fill='blue',bins=10)+ggtitle("UAH Histogram")

h_OPS_GSC<-GSC %>% 
  ggplot(aes(OPS)) + 
  geom_histogram(color='yellow', fill='red',bins=10)+ggtitle("GSC Histogram")

b_OPS_AUM<-AUM %>% ggplot(aes(OPS)) + geom_bar(color= 'orange', fill='black')+ggtitle("AUM Barplot")

b_OPS_UAH<-UAH %>% ggplot(aes(OPS)) + geom_bar(color= 'blue', fill='black')+ggtitle("AUM Barplot")

b_OPS_GSC<-GSC %>% ggplot(aes(OPS)) + geom_bar(color= 'red', fill='yellow')+ggtitle("GSC Barplot")

grid.arrange(bp_OPS_AUM,bp_OPS_UAH,bp_OPS_GSC,qq_OPS_AUM,qq_OPS_UAH,qq_OPS_GSC,
             d_OPS_AUM,d_OPS_UAH,d_OPS_GSC,h_OPS_AUM,h_OPS_UAH,h_OPS_GSC,
             b_OPS_AUM,b_OPS_UAH,b_OPS_GSC, ncol = 3 )
``` 


